# permissions for end users to view controlledjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controlledjob-viewer-role
rules:
- apiGroups:
  - batch.jmarkp.uk
  resources:
  - controlledjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.jmarkp.uk
  resources:
  - controlledjobs/status
  verbs:
  - get
