apiVersion: batch.jmarkp.uk/v1
kind: ControlledJob
metadata:
  name: controlledjob-sample
spec:
  timezone:
    name: "GMT"
  events:
    - action: "start"
      schedule:
        timeOfDay: "22:27"
        daysOfWeek: "MON-FRI"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
